# 0: Trace, 1: Debug, 2: Error
log: 1

infer:
  map: beginner

train:
  map: beginner
  should_resume: False
  should_save: False
  should_compile: False
  collector:
    # TODO: Change to 300
    frames_per_batch: 50
    batches: 2
  optimizer:
    lr: 0.00025
    epsilon: 0.000001 # Small value added to numbers in optimizers to prevent division by zero.
    weight_decay: 0.0 # Discourages large weights to prevent overfitting. 0.0 means unused.
    anneal_lr: True # Gradually reduces the learning rate during training.
  loss:
    mini_batches_per_batch: 4
    gamma: 0.99 # Higher means future rewards are valued more than immediate rewards.
    ppo_epochs: 5 # Number of times each mini batch is used during training.
    gae_lambda: 0.95 # Smoothens GAE, changing bias vs variance balance in advantage. High value is high variance.
    clip_epsilon: 0.2 # Controls clipping range to prevent drastic changes.
    anneal_clip_epsilon: True # Reduces clipping value over time to gradually make adjustments smaller.
    critic_coefficient: 0.95 # How much the critic loss contributes to the total loss.
    entropy_coefficient: 0.02 # Improves exploration by adding entropy loss to the optimization objective. High value is more exploration.
    max_gradient_norm: 1.2 # For gradient clipping to prevent exploding gradients by capping their norm.
    loss_critic_type: l2 # Critic loss function type. L2 is Mean Squared Error.

model:
  results_dir: results
  img_size: 500

env:
  name: SurfChan
  game_speed: 3.0
  seconds_to_finish: 6

css:
  close_on_script_close: True

server:
  host: 127.0.0.1
  port: 27015
  close_on_script_close: True

gui:
  host: 127.0.0.1
  port: 27016

maps:
  beginner:
    start_angle: 90.0
    start: [-128.0, 0.0, 372.0]
    finish: [-140, 2008, -376]
    ground: -424.0
